### PR TITLE
add new wacca charts

### PR DESCRIPTION
**Pull request by cg505**
There is one new song added to the game every day until I think July 19, so there will be a lot more. This is the first batch.
The script was updated to avoid removing songs that are gone from the website. A bunch of songs were removed from the game and they finally took them off the website so this avoids that issue. I may file another PR that removes them from the "reverse" version, but it's not happening in this one.
Test failures were introduced by AI table update in a prior commit, all the wacca tests pass.
Hope all is well :pray: and thanks for taking a look.

### CODE REVIEW

**Comment by zkldi** [comment]
thanks for yr continued support & work

**Comment by zkldi** [comment]
heads up: everything is getting moved to a monorepo (https://github.com/TNG-dev/Tachi) at some point.
we're mostly pinned by the sheer magnitude of devops work, but it'll be generally way nicer.

**Comment by zkldi** [comment]
backported to production

**Comment by cg505** [comment]
lmk if there's anything you need help from me on the monorepo front, that will be sick

**Pull request merged**
