### PR TITLE
Casthour songs with existing info added to Infinitas table

### PR DESCRIPTION
**Pull request by justOkapi**

### CODE REVIEW

**Comment by zkldi** [comment]
As mentioned on discord, this PR needs to add the new charts before it can be merged. At the moment the new songs don't have any child charts, when they definitely should.

**Comment by zkldi** [comment]
will look more into this PR soon, wasn't expecting the beginner stuff to be added onto this branch.

**Comment by zkldi** [comment]
ergo
Fixes #33

**Comment by zkldi** [comment]
I'm assuming this PR is all finished and stuff. It'll be merged soon enough but will require a parallel script in tachi-server to remove beginner scores.

**Comment by justOkapi** [comment]
I haven't done the urafumen beginners yet but that's easy enough

**Comment by zkldi** [comment]
going to take control of this branch and sever it before the no-beginners work. will be easier to apply (see: review) this in two parts.

**Comment by zkldi** [comment]
Superceded by #58

**Pull request closed without merging**
