### PR TITLE
add konaste version to recently added charts

### PR DESCRIPTION
**Pull request by cg505**
https://twitter.com/SOUNDVOLTEX573/status/1519573407461175296
https://twitter.com/SOUNDVOLTEX573/status/1519573672662831105 
Songs technically aren't available until 5/2 but whatever.
Thanks to hibiki ofc

### CODE REVIEW

**Comment by zkldi** [comment]
wait what sorry these songs aren't available for like 4 days? damn

i've merged it now you can all deal with the consequences

**Comment by cg505** [comment]
I mean the game is already updated, but the songs won't be available to play until then

**Comment by zkldi** [comment]
Yeah, will just result in unlampable folders for a couple days. I'm sure people will live.

**Comment by cg505** [comment]
yep

**Comment by cg505** [comment]
I mean, they were already unlampable before yesterday anyway loll

**Pull request merged**
